Repository atlp-rwanda/commanders-rn-medica, pull requests merged in 2024-06, with the labels that each got.

#82 Feature : Write review screen
  app/Appointments/doctorcard/star.tsx
  app/Appointments/index.tsx
  app/Appointments/reschedul.tsx
  app/Appointments/resonforcancel.tsx
  app/Appointments/voice-call/session-ended.tsx
  app/Appointments/voice-call/writeReview.tsx
  assets/appointmentIcon/review.png
  assets/doctors/Ellipse.png
  package-lock.json
  package.json
Labels: Feature, Need Review

#72 Feature: Add voice calls history screens
  app/chat-history/chatHistory.tsx
  app/chat-history/singleCall.tsx
  app/chat-history/voiceCalls.tsx
  assets/Travis-Mafia.mp3
  assets/icons/arrow.ts
  assets/icons/phone.ts
  assets/icons/playBtn.ts
  assets/images/chat/waves.png
  components/buttonModified.tsx
  components/chats/voiceCard.tsx
Labels: Feature, Need Review

#70 Feature: Contact help center
  app/settings/customerService.tsx
  app/settings/help.tsx
  assets/contact/call.png
  assets/contact/facebook.png
  assets/contact/headset.png
  assets/contact/instagram.png
  assets/contact/twitter.png
  assets/contact/website.png
  assets/contact/whatsapp.png
  assets/icons/file.ts
  assets/icons/menu.ts
  assets/icons/recorder.ts
  components/camera/camera.tsx
  components/cards/faqButtons.tsx
  components/chatInput.tsx
  components/chats/chat.tsx
  components/faqSearch.tsx
  components/recording.tsx
  components/utils.ts
  package-lock.json
  package.json
Labels: Feature, Need Review

#86 Feature: Messaging Appointment Chat Screen
  app/Appointments/details.tsx
  app/messagingAppointment/messaging.tsx
  assets/icons/search.png
  components/chatInput.tsx
Labels: Feature, Need Review

#84 chore(supabase): Set up Supabase as backend service and add initial tests (#83)
  app/signupSignin/SignIn.tsx
  app/signupSignin/SignUp.tsx
  app/supabase.tsx
  package-lock.json
  package.json
Labels: Chore, Need Review

#94 Feature: fill up profile and sign in and signup implementation
  app/(tabs)/_layout.tsx
  app/Userprofile/createpin.tsx
  app/Userprofile/setfingerprint.tsx
  app/Userprofile/userprofile.tsx
  app/signupSignin/SignIn.tsx
  app/signupSignin/SignUp.tsx
  app/signupSignin/index.tsx
  package-lock.json
  package.json
Labels: Feature, Need Review

#93 Feature: Reset password with email implementation
  app/reset-password/index.tsx
  app/reset-password/new-password.tsx
  app/reset-password/verify-code.tsx
  app/signupSignin/SignIn.tsx
  app/supabase.tsx
  components/Header.tsx
  components/Input.tsx
  package-lock.json
  package.json
Labels: Feature, Need Review

#97 Feature: User profile integration
  .gitignore
  app/(tabs)/index.tsx
  app/(tabs)/profile.tsx
  app/Userprofile/userprofile.tsx
  app/settings/editProfile.tsx
  app/supabase.tsx
  components/settings/logoutModal.tsx
  package-lock.json
  package.json
  utils/profile.ts
Labels: Feature, Need Review

#104 Feature: doctors detail implementation
  .gitignore
  app/(tabs)/index.tsx
  app/Doctors/doctorsFound.tsx
  app/Doctors/favoriteDoctors.tsx
  app/Doctors/topDoctors.tsx
  app/reset-password/index.tsx
  app/reset-password/new-password.tsx
  app/reset-password/verify-code.tsx
  components/cards/doctCard.tsx
  components/cards/doctorCard.tsx
  package-lock.json
  package.json
Labels: Feature

#107 Fix: Onboarding screens to display only on first launch of the app
  app/index.tsx
  app/signupSignin/index.tsx
  jest.config.json
  jest.setup.js
  tsconfig.json
Labels: Fix, Need Review

#111 Feature:book appointment implementation
  app/(tabs)/index.tsx
  app/Appointments/index.tsx
  app/doctor-appointments/book-appointment.tsx
  app/doctor-appointments/index.tsx
  app/doctor-appointments/patient-details.tsx
  app/doctor-appointments/review-summary.tsx
  app/doctor-appointments/select-package.tsx
Labels: Feature, Need Review

#101 Feature forgot password with phone number
  app/(tabs)/index.tsx
  app/(tabs)/profile.tsx
  app/reset-password/index.tsx
  app/reset-password/new-password.tsx
  app/reset-password/verify-code.tsx
  app/settings/editProfile.tsx
  assets/icons/infoCircle.ts
  components/button.tsx
  package-lock.json
  package.json
  redux/actions/profile.ts
  redux/reducers/profile.ts
  redux/store/store.ts
  utils/profile.ts
Labels: need aprove, Feature

#117 Feature: Apple login
  app.json
  app/Userprofile/userprofile.tsx
  app/signupSignin/SignIn.tsx
  app/signupSignin/index.tsx
  components/SignInButton.tsx
  components/SignUpWith.tsx
  package-lock.json
  package.json
Labels: need aprove, Feature

#105 Feature: Sign in with google
  .gitignore
  app/Userprofile/createpin.tsx
  app/Userprofile/setfingerprint.tsx
  app/Userprofile/userprofile.tsx
  app/index.tsx
  app/pin/index.tsx
  app/signupSignin/SignIn.tsx
  app/signupSignin/SignUp.tsx
  app/signupSignin/index.tsx
  commanders-rn-medica.code-workspace
  components/SignInButton.tsx
  components/SignUpWith.tsx
  eas.json
  package-lock.json
  package.json
Labels: need aprove, Feature

#112 Feature: about doctors & Reviews
  app/Doctors/topDoctors.tsx
  app/doctor-appointments/index.tsx
  components/cards/doctorCard.tsx
  components/cards/reiews/review.tsx
  package-lock.json
  package.json
  redux/Thunk/doctorThunk.ts
  redux/reducers/doctors.ts
  redux/store/store.ts
Labels: Feature

#125 Feature: Adding, removing and viewing favorite doctors.
  .gitignore
  app/(tabs)/index.tsx
  app/Doctors/favoriteDoctors.tsx
  app/Doctors/topDoctors.tsx
  app/doctor-appointments/index.tsx
  components/cards/reiews/review.tsx
  package-lock.json
  package.json
  redux/Thunk/doctorThunk.ts
  redux/reducers/doctors.ts
Labels: Feature, Need Review
