Repository atlp-rwanda/commanders-rn-medica, pull requests merged in 2024-05, with the labels that each got.

#11 Project setup
  .gitignore
  app.json
  app/index.tsx
  assets/adaptive-icon.png
  assets/favicon.png
  assets/icon.png
  assets/splash.png
  babel.config.js
  components/button.tsx
  package.json
  styles/common.ts
  tsconfig.json
  yarn.lock
Labels: Chore

#10 ch-workflow-superLinter
  .github/workflows/.prettierrc
  .github/workflows/linter.yml
Labels: Chore

#14 Setup redux
  .gitignore
  App.tsx
  app/_layout.tsx
  app/counter/Counter.tsx
  app/index.tsx
  jest.config.json
  package-lock.json
  package.json
  redux/reducers/counter.ts
  redux/store/store.ts
Labels: Chore

#23 Feature: Home screen & Action Menu
  app.json
  app/(tabs)/_layout.tsx
  app/(tabs)/appointment.tsx
  app/(tabs)/articles.tsx
  app/(tabs)/history.tsx
  app/(tabs)/index.tsx
  app/(tabs)/profile.tsx
  app/_layout.tsx
  app/index.tsx
  assets/doctors/doctor.png
  assets/doctors/heart.png
  assets/doctors/star.png
  assets/icons/appointment.ts
  assets/icons/articles.ts
  assets/icons/dentist.ts
  assets/icons/filter.ts
  assets/icons/general.ts
  assets/icons/heart.ts
  assets/icons/history.ts
  assets/icons/home.ts
  assets/icons/index.ts
  assets/icons/more.ts
  assets/icons/neurologist.ts
  assets/icons/notification.ts
  assets/icons/nutritionist.ts
  assets/icons/opthamologist.ts
  assets/icons/pediatric.ts
  assets/icons/profile.ts
  assets/icons/radiologist.ts
  assets/icons/search.ts
  assets/images/bannerImg.png
  assets/images/profilePicture.png
  components/button.tsx
  components/cards/doctorCard.tsx
  components/carousel.tsx
  components/searchInput.tsx
  package-lock.json
  package.json
  tailwind.config.js
Labels: Feature

#27 Feat: add password reset screens
  .gitignore
  app.json
  app/_layout.tsx
  app/index.tsx
  app/reset-password/_layout.tsx
  app/reset-password/index.tsx
  app/reset-password/new-password.tsx
  app/reset-password/verify-code.tsx
  assets/icons/back.png
  assets/icons/chat.png
  assets/icons/hide.png
  assets/icons/lock.png
  assets/icons/message.png
  assets/images/forgot-password/frame-2.png
  assets/images/forgot-password/frame.png
  assets/images/forgot-password/loading-frame.png
  assets/images/forgot-password/success-frame.png
  components/Icon.tsx
  components/Input.tsx
  components/NavigationHeader.tsx
  components/button.tsx
  package-lock.json
  package.json
  tsconfig.json
Labels: Feature

#34 Feature: Sign Up and Sing In
  .github/workflows/linter.yml
  app/signupSignin/LetsYouIn.tsx
  app/signupSignin/SignUp.tsx
  app/signupSignin/SingIn.tsx
  assets/Account.png
  assets/Frame.png
  assets/apple-logo.png
  assets/apple.png
  assets/facebook-logo.png
  assets/facebook.png
  assets/google-logo.png
  assets/google.png
  components/BackIcon.tsx
  components/EmailPasswordInput.tsx
  components/Or.tsx
  components/RememberMe.tsx
  components/SignInButton.tsx
  components/SignUpText.tsx
  components/SignUpWith.tsx
  components/button.tsx
  styles/common.ts
Labels: Feature

#42 Add Create pin and set up fingerprint screens
  app/Userprofile/createpin.tsx
  app/Userprofile/setfingerprint.tsx
  app/Userprofile/userprofile.tsx
  app/_layout.tsx
  assets/icons/userprofile/confirmprofile.png
  assets/icons/userprofile/icons.ts
  package-lock.json
  package.json
  tailwind.config.js
Labels: Feature

#32 Feature: notifications screen and notification component design
  app/(tabs)/index.tsx
  app/_layout.tsx
  app/index.tsx
  app/notifications/_layout.tsx
  app/notifications/index.tsx
  assets/icons/arrow-left.png
  assets/icons/calendar-info.png
  assets/icons/calendar.png
  assets/icons/close-square.png
  assets/icons/more-circle.png
  assets/icons/ticket.png
  assets/icons/wallet.png
  components/Icon.tsx
  components/NavigationHeader.tsx
  components/ThemedText.tsx
  components/cards/doctorCard.tsx
  components/carousel.tsx
  components/notifications/notification.tsx
  components/searchInput.tsx
  package-lock.json
  package.json
  tailwind.config.js
Labels: Feature

#45 Fix: Home screen styling
  app/(tabs)/_layout.tsx
  app/(tabs)/index.tsx
  app/reset-password/index.tsx
  app/reset-password/new-password.tsx
  app/reset-password/verify-code.tsx
  assets/doctors/doctor1.png
  assets/doctors/doctor2.png
  assets/doctors/doctor3.png
  assets/images/bannerImg.png
  assets/images/profilePicture.png
  components/cards/doctorCard.tsx
  components/carousel.tsx
  components/searchInput.tsx
  package-lock.json
  package.json
  tailwind.config.js
Labels: Fix

#52 Feature: Doctors search and filter screens
  app/(tabs)/index.tsx
  app/Doctors/doctorsFound.tsx
  app/Doctors/favoriteDoctors.tsx
  app/Doctors/searchDoctor.tsx
  app/Doctors/searchNotFound.tsx
  app/Doctors/topDoctors.tsx
  app/index.tsx
  assets/doctors/arrows.png
  assets/doctors/astar.png
  assets/doctors/doc1.png
  assets/doctors/doc2.png
  assets/doctors/doc3.png
  assets/doctors/doc4.png
  assets/doctors/doc5.png
  assets/doctors/heart.png
  assets/doctors/like.png
  assets/doctors/loading.png
  assets/doctors/menu.png
  assets/doctors/notfound.png
  assets/doctors/searchIcon.png
  assets/doctors/star.png
  assets/doctors/whitestar.png
  assets/icons/focus.ts
  components/cards/DocButtons.tsx
  components/cards/ReviewButtons.tsx
  components/cards/doctCard.tsx
  components/searchinput2.tsx
Labels: Feature

#41 Revert "Feature: Sign Up and Sign In (#34)"
  .github/workflows/linter.yml
  app/signupSignin/LetsYouIn.tsx
  app/signupSignin/SignUp.tsx
  app/signupSignin/SingIn.tsx
  assets/Account.png
  assets/Frame.png
  assets/apple-logo.png
  assets/apple.png
  assets/facebook-logo.png
  assets/facebook.png
  assets/google-logo.png
  assets/google.png
  components/BackIcon.tsx
  components/EmailPasswordInput.tsx
  components/Or.tsx
  components/RememberMe.tsx
  components/SignInButton.tsx
  components/SignUpText.tsx
  components/SignUpWith.tsx
  components/button.tsx
  styles/common.ts
Labels: Fix

#50 Feature: book doctor appointments screens
  app/(tabs)/_layout.tsx
  app/(tabs)/index.tsx
  app/doctor-appointments/_layout.tsx
  app/doctor-appointments/book-appointment.tsx
  app/doctor-appointments/index.tsx
  app/doctor-appointments/patient-details.tsx
  app/doctor-appointments/reviews.tsx
  app/doctor-appointments/select-package.tsx
  app/index.tsx
  assets/icons/activity.ts
  assets/icons/arrow.ts
  assets/icons/call.ts
  assets/icons/chat.ts
  assets/icons/heart.ts
  assets/icons/more.ts
  assets/icons/star.ts
  assets/icons/time.ts
  assets/icons/user.ts
  assets/icons/video.ts
  assets/reviewers/aileen.png
  assets/reviewers/charolette.png
  assets/reviewers/darron.png
  assets/reviewers/lauralee.png
  assets/reviewers/rodolfo.png
  components/Input.tsx
  components/NavigationHeader.tsx
  components/ThemedText.tsx
  components/button.tsx
  components/cards/calendar.tsx
  components/cards/doctorCard.tsx
  components/cards/doctors/MinimalDoctorCard.tsx
  components/cards/packages/package.tsx
  components/cards/reiews/review.tsx
  components/radio.tsx
  components/select.tsx
  package-lock.json
  package.json
  redux/reducers/counter.ts
  redux/reducers/doctors.ts
  redux/store/store.ts
  tailwind.config.js
Labels: Feature

#63 Chore: Add README.md to Repository
  README.md
Labels: documentation

#66 Feature: Add onboarding screen
  app/RotatingImage.tsx
  app/index.tsx
  assets/MedicaLogo.png
  assets/Spinner.png
  assets/icon.png
  assets/images/onboarding/MedicaWelcome.png
  assets/images/onboarding/onboarding1.jpg
  assets/images/onboarding/onboarding2.jpg
  assets/images/onboarding/onboarding3.jpg
  assets/images/onboarding/welcome.png
  assets/splash.png
  package-lock.json
  package.json
Labels: Feature, Need Review

#67 Feature: Creating user profile UI
  app/(tabs)/profile.tsx
  app/_layout.tsx
  app/settings/editProfile.tsx
  app/settings/friends.tsx
  app/settings/help.tsx
  app/settings/language.tsx
  app/settings/notification.tsx
  app/settings/payment.tsx
  app/settings/security.tsx
  app/signupSignin/SignIn.tsx
  app/signupSignin/SignUp.tsx
  app/signupSignin/index.tsx
  assets/doctors/doc1.png
  assets/icons/edit.ts
  assets/icons/medica-logo.ts
  assets/icons/more.ts
  assets/icons/profile.ts
  assets/icons/settings/applePay.ts
  assets/icons/settings/arrowRight.ts
  assets/icons/settings/eye.ts
  assets/icons/settings/friends.ts
  assets/icons/settings/googlePay.ts
  assets/icons/settings/index.ts
  assets/icons/settings/info.ts
  assets/icons/settings/language.ts
  assets/icons/settings/logout.ts
  assets/icons/settings/masterCard.ts
  assets/icons/settings/paypal.ts
  assets/icons/settings/scan.ts
  assets/icons/settings/shieldDone.ts
  assets/icons/settings/wallet.ts
  components/button.tsx
  components/cards/doctCard.tsx
  components/common/touchable.tsx
  components/settings/logoutModal.tsx
  components/settings/notifCard.tsx
  components/settings/payCard.tsx
  components/settings/securityCard.tsx
  components/settings/settingCard.tsx
  package-lock.json
  package.json
  tailwind.config.js
Labels: Feature, Need Review

#62 Feature:Invite settings screen
  app/index.tsx
  app/settings/friends.tsx
  assets/friends/aileen.png
  assets/friends/charolette.png
  assets/friends/darron.png
  assets/friends/lauralee.png
  assets/friends/rodolfo.png
Labels: Feature, Need Review

#57 Feature: Chat history and single chat view screens
  app/(tabs)/history.tsx
  app/chat-history/chatHistory.tsx
  app/chat-history/data.ts
  assets/icons/delete.ts
  assets/icons/doubletick.ts
  assets/icons/download.ts
  assets/icons/more.ts
  assets/icons/search.ts
  assets/images/chat/doc1.png
  assets/images/chat/doc2.png
  assets/images/chat/doc3.png
  assets/images/chat/doc4.png
  assets/images/chat/doc5.png
  assets/images/chat/doc6.png
  assets/images/chat/doc7.png
  assets/images/chat/leg.png
  assets/images/chat/leg1.png
  assets/images/chat/logo.png
  components/chats/chat.tsx
Labels: Feature, Need Review

#55 Fix: Doctor search and filter screens styling
  app/(tabs)/index.tsx
  app/Doctors/doctorsFound.tsx
  app/Doctors/favoriteDoctors.tsx
  app/Doctors/searchDoctor.tsx
  app/Doctors/searchNotFound.tsx
  app/Doctors/topDoctors.tsx
  app/Userprofile/setfingerprint.tsx
  app/index.tsx
  components/searchinput2.tsx
Labels: Fix

#69 Feature: doctor appointment payment screens
  app/Userprofile/createpin.tsx
  app/chat-history/chatHistory.tsx
  app/doctor-appointments/_layout.tsx
  app/doctor-appointments/add-card.tsx
  app/doctor-appointments/patient-details.tsx
  app/doctor-appointments/payments.tsx
  app/doctor-appointments/review-summary.tsx
  app/doctor-appointments/select-package.tsx
  app/index.tsx
  app/pin/_layout.tsx
  app/pin/index.tsx
  app/signupSignin/SignIn.tsx
  app/signupSignin/SignUp.tsx
  app/signupSignin/index.tsx
  assets/Account.png
  assets/Frame.png
  assets/apple-logo.png
  assets/apple.png
  assets/checked.png
  assets/facebook-logo.png
  assets/facebook.png
  assets/friends/aileen.png
  assets/friends/charolette.png
  assets/friends/darron.png
  assets/friends/lauralee.png
  assets/friends/rodolfo.png
  assets/google-logo.png
  assets/google.png
  assets/icons/amazon.ts
  assets/icons/apple.ts
  assets/icons/google.ts
  assets/icons/mastercard.ts
  assets/icons/paypal.ts
  assets/icons/scan.ts
  assets/images/card/background.png
  assets/images/modals/failed-bg.png
  assets/images/modals/success-bg.png
  assets/reviewers/aileen.png
  assets/reviewers/charolette.png
  assets/reviewers/darron.png
  assets/reviewers/lauralee.png
  assets/reviewers/rodolfo.png
  assets/unchecked.png
  components/BackIcon.tsx
  components/Input.tsx
  components/RememberMe.tsx
  components/SignInButton.tsx
  components/SignUpWith.tsx
  components/button.tsx
  components/spinner.tsx
Labels: Feature, Need Review

#49 Feature: Schedule Appointment screen
  app/(tabs)/appointment.tsx
  app/(tabs)/articles.tsx
  app/Appointments/doctorcard/calendal.tsx
  app/Appointments/doctorcard/cards.tsx
  app/Appointments/doctorcard/cardss.tsx
  app/Appointments/doctorcard/checkbox.tsx
  app/Appointments/index.tsx
  app/Appointments/reschedul.tsx
  app/Appointments/resonforcancel.tsx
  app/Appointments/selectdate.tsx
  assets/Tomasi.jpeg
  assets/appointmentIcon/Arcal.png
  assets/appointmentIcon/Arcl1.png
  assets/appointmentIcon/Group.png
  assets/appointmentIcon/Group1.png
  assets/appointmentIcon/first.png
  assets/appointmentIcon/message.png
  assets/appointmentIcon/video.png
  assets/appointmentIcon/voice.png
  assets/colling.png
  package-lock.json
  package.json
Labels: Need Review

#78 Feature: appointment voice call
  app/(tabs)/appointment.tsx
  app/Appointments/_layout.tsx
  app/Appointments/doctorcard/cards.tsx
  app/Appointments/doctorcard/cardss.tsx
  app/Appointments/index.tsx
  app/Appointments/voice-call/_layout.tsx
  app/Appointments/voice-call/call.tsx
  app/Appointments/voice-call/index.tsx
  app/Appointments/voice-call/session-ended.tsx
  app/doctor-appointments/select-package.tsx
  assets/icons/arrow.ts
  assets/icons/call.ts
  assets/icons/loudspeaker.ts
  assets/icons/voice.ts
  assets/images/time-bg.png
  components/NavigationHeader.tsx
  components/cards/packages/package.tsx
  package-lock.json
  package.json
  redux/reducers/doctors.ts
Labels: Feature, Need Review

#79 Feature: Video call appointment
  app.json
  app/Appointments/details.tsx
  app/Appointments/doctorcard/cardss.tsx
  app/chat/index.tsx
  app/videoCallAppointment/index.tsx
  app/videoCallAppointment/videoCall.tsx
  assets/icons/arrow.ts
  assets/icons/attach.ts
  assets/icons/call.ts
  assets/icons/camera.ts
  assets/icons/chat.ts
  assets/icons/emoji.ts
  assets/icons/endCall.ts
  assets/icons/video.ts
  assets/icons/voice.ts
  assets/icons/volume.ts
  components/button.tsx
  components/camera/camera.tsx
  components/cards/packages/appointmentPackage.tsx
  package-lock.json
  package.json
  redux/reducers/calls.ts
  redux/store/store.ts
Labels: Feature, Need Review
