Repository atlp-rwanda/commanders-rn-medica, pull requests merged in 2024-07, with the labels that each got.

#121 Feature: Payment implementation
  app/Appointments/index.tsx
  app/doctor-appointments/_layout.tsx
  app/doctor-appointments/add-card.tsx
  app/doctor-appointments/patient-details.tsx
  app/doctor-appointments/payments.tsx
  app/doctor-appointments/review-summary.tsx
  app/doctor-appointments/select-package.tsx
  components/cards/doctors/MinimalDoctorCard.tsx
  package-lock.json
  package.json
Labels: Feature, Need Review

#106 Feature: Facebook sign in
  .idea/workspace.xml
  .vscode/settings.json
  android/.gitignore
  android/app/build.gradle
  android/app/debug.keystore
  android/app/proguard-rules.pro
  android/app/src/debug/AndroidManifest.xml
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/andela/commanders/medica/MainActivity.kt
  android/app/src/main/java/com/andela/commanders/medica/MainApplication.kt
  android/app/src/main/res/drawable-hdpi/splashscreen_image.png
  android/app/src/main/res/drawable-mdpi/splashscreen_image.png
  android/app/src/main/res/drawable-xhdpi/splashscreen_image.png
  android/app/src/main/res/drawable-xxhdpi/splashscreen_image.png
  android/app/src/main/res/drawable-xxxhdpi/splashscreen_image.png
  android/app/src/main/res/drawable/rn_edit_text_material.xml
  android/app/src/main/res/drawable/splashscreen.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  android/app/src/main/res/values-night/colors.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/styles.xml
  android/build.gradle
  android/gradle.properties
  android/gradle/wrapper/gradle-wrapper.jar
  android/gradle/wrapper/gradle-wrapper.properties
  android/gradlew
  android/gradlew.bat
  android/settings.gradle
  app.json
  app/Userprofile/userprofile.tsx
  app/signupSignin/index.tsx
  app/supabase.tsx
  babel.config.js
  components/SignInButton.tsx
  components/SignUpWith.tsx
  eas.json
  redux/reducers/session.ts
  redux/store/store.ts
Labels: Feature, Need Review

#126 Chore: Stream setup
  app.json
  app/_layout.tsx
  package-lock.json
  package.json
  utils/stream.ts
Labels: Chore, Need Review

#127 Fix: Remove android folder from the code base
  .idea/workspace.xml
  .vscode/settings.json
  android/.gitignore
  android/app/build.gradle
  android/app/debug.keystore
  android/app/proguard-rules.pro
  android/app/src/debug/AndroidManifest.xml
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/andela/commanders/medica/MainActivity.kt
  android/app/src/main/java/com/andela/commanders/medica/MainApplication.kt
  android/app/src/main/res/drawable-hdpi/splashscreen_image.png
  android/app/src/main/res/drawable-mdpi/splashscreen_image.png
  android/app/src/main/res/drawable-xhdpi/splashscreen_image.png
  android/app/src/main/res/drawable-xxhdpi/splashscreen_image.png
  android/app/src/main/res/drawable-xxxhdpi/splashscreen_image.png
  android/app/src/main/res/drawable/rn_edit_text_material.xml
  android/app/src/main/res/drawable/splashscreen.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  android/app/src/main/res/values-night/colors.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/styles.xml
  android/build.gradle
  android/gradle.properties
  android/gradle/wrapper/gradle-wrapper.jar
  android/gradle/wrapper/gradle-wrapper.properties
  android/gradlew
  android/gradlew.bat
  android/settings.gradle
Labels: Fix, Need Review

#132 fix:(stream setup)
  app/_layout.tsx
Labels: Fix, Need Review

#123 Feature profile and settings management #120
  app.json
  app/(tabs)/_layout.tsx
  app/(tabs)/index.tsx
  app/(tabs)/profile.tsx
  app/i18n.tsx
  app/index.tsx
  app/settings/friends.tsx
  app/settings/language.tsx
  app/settings/notification.tsx
  app/signupSignin/SignIn.tsx
  app/signupSignin/SignUp.tsx
  app/signupSignin/index.tsx
  components/RememberMe.tsx
  components/carousel.tsx
  components/searchInput.tsx
  locales/Arabic.json
  locales/Chinese.json
  locales/Fulani.json
  locales/Hausa.json
  locales/Luganda.json
  locales/Mandarin.json
  locales/Russian.json
  locales/Shona.json
  locales/Spanish.json
  locales/Swahili.json
  locales/Yoruba.json
  locales/en.json
  locales/fr.json
  locales/kinyarwanda.json
  package-lock.json
  package.json
Labels: Feature, Need Review

#131 Ft- updating and cancel appointment
  app/Appointments/doctorcard/calendal.tsx
  app/Appointments/doctorcard/cardss.tsx
  app/Appointments/index.tsx
  app/Appointments/reschedul.tsx
  app/Appointments/resonforcancel.tsx
  app/Appointments/selectdate.tsx
Labels: Feature, Need Review

#135 feature:messaging appointment implementation
  app/Appointments/details.tsx
  app/Appointments/doctorcard/cardss.tsx
  app/Appointments/index.tsx
  app/messagingAppointment/messaging.tsx
  app/supabase.tsx
  assets/icons/send.ts
  components/SendMessageButton.tsx
  components/SignInButton.tsx
  components/chatInput.tsx
  components/recording.tsx
  package-lock.json
  package.json
  redux/reducers/appointment.ts
  redux/reducers/doctors.ts
  redux/store/store.ts
Labels: Feature

#146 Feature:Sending-media-via-messaging implementation
  app/messagingAppointment/messaging.tsx
  assets/icons/file.ts
  assets/icons/playBtn.ts
  components/AudioPlayer.tsx
  components/chatInput.tsx
  components/chats/chat.tsx
  components/recording.tsx
  package-lock.json
  package.json
  utils/checkSession.ts
  utils/upload.ts
Labels: need aprove, Chore, Feature

#150 Feature: search implementation #149
  app/(tabs)/index.tsx
  app/Doctors/doctorsFound.tsx
  app/Doctors/favoriteDoctors.tsx
  app/Doctors/searchDoctor.tsx
  app/Doctors/searchNotFound.tsx
  app/Doctors/topDoctors.tsx
  components/cards/DocButtons.tsx
  components/cards/ReviewButtons.tsx
  components/cards/doctCard.tsx
  components/cards/doctorCard.tsx
  components/searchinput2.tsx
  redux/reducers/doctors.ts
Labels: need aprove, Feature

#137 feature: Implementing Local Security Features
  app/Userprofile/createpin.tsx
  app/_layout.tsx
  app/settings/security.tsx
  app/signupSignin/SignIn.tsx
  components/RememberMe.tsx
  components/settings/securityCard.tsx
Labels: need aprove, Feature

#153 Feature: Voice & Video Call
  android/app/build.gradle
  android/app/proguard-rules.pro
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/andela/commanders/medica/MainActivity.kt
  android/app/src/main/res/values/colors.xml
  android/gradle.properties
  app.json
  app/Appointments/details.tsx
  app/Appointments/voice-call/call.tsx
  app/_layout.tsx
  app/doctor-appointments/review-summary.tsx
  app/i18n.tsx
  package-lock.json
  package.json
  utils/api.ts
  utils/permissionsRquest.ts
  utils/stream.ts
Labels: Feature, Need Review

#140 Feature write your review implemetation
  app/(tabs)/index.tsx
  app/Appointments/doctorcard/cardss.tsx
  app/Appointments/doctorcard/star.tsx
  app/Appointments/index.tsx
  app/Appointments/voice-call/writeReview.tsx
  app/doctor-appointments/index.tsx
  app/doctor-appointments/reviews.tsx
  components/cards/doctCard.tsx
  components/cards/reiews/review.tsx
Labels: need aprove, Feature, Need Review

#154 Feature: History chats calls implementation
  app/(tabs)/articles.tsx
  app/(tabs)/profile.tsx
  app/Appointments/voice-call/writeReview.tsx
  app/Doctors/searchDoctor.tsx
  app/articles/ArticlesDetails.tsx
  app/articles/ArticlesPage.tsx
  app/articles/BookMarkedArticle.tsx
  app/articles/SeeAllArticles.tsx
  app/chat-history/VideoCall.tsx
  app/chat-history/VideoRecord.tsx
  app/chat-history/chatHistory.tsx
  app/chat-history/singleCall.tsx
  app/chat-history/voiceCalls.tsx
  app/doctor-appointments/index.tsx
  app/settings/friends.tsx
  components/cards/DoctorVideo.tsx
  components/chats/voiceCard.tsx
Labels: Feature, Need Review

#155 Fix: Remove Unused Icons and Fix app Issues
  app/Appointments/details.tsx
  app/Appointments/index.tsx
  app/Appointments/voice-call/index.tsx
  app/articles/ArticlesDetails.tsx
  app/articles/ArticlesPage.tsx
  app/articles/BookMarkedArticle.tsx
  app/articles/SeeAllArticles.tsx
  app/messagingAppointment/messaging.tsx
  assets/icons/cardiologist.ts
  assets/icons/index.ts
  assets/icons/pediatrician.ts
  components/cards/DocButtons.tsx
  components/cards/packages/appointmentPackage.tsx
Labels: Fix
